services:
  server:
    build:
      context: ./express
      args:
        - NODE_ENV=production
    ports:
      - 4000:4000
    depends_on:
      - redis
      - db
    networks:
      - default
  db:
    image: postgres:14.3-alpine
    ports:
      - 5432:5432
    volumes:
      - pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
  redis:
    image: redis:7.0.2-alpine
    ports:
      - 6379:6379
    expose:
      - "6379"
    volumes:
      - ./express/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - default
  kafka:
    image: bitnami/kafka:latest
    ports:
      - 9092:9092
    volumes:
      - kafka:/bitnami/kafka
    networks:
      - default
    depends_on:
      - zookeeper
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    networks:
      - default
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

volumes:
  pgdb:

networks:
  default:
